name: CI Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
        
      - name: Build application
        run: npm run build
        
      - name: Run Playwright tests
        run: npm run test
        
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
          
      - name: Check for visual regression artifacts
        id: check-testivai
        run: |
          if [ -d ".testivai" ] && [ "$(find .testivai -type f | wc -l)" -gt 0 ]; then
            echo "artifacts-exist=true" >> $GITHUB_OUTPUT
          else
            echo "artifacts-exist=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Upload visual regression artifacts
        uses: actions/upload-artifact@v4
        if: always() && steps.check-testivai.outputs.artifacts-exist == 'true'
        with:
          name: visual-regression-results
          path: .testivai/
          retention-days: 30
